all:				EchoServer.class EchoClient.class

EchoServer.class:		EchoServer.java
				@javac EchoServer.java

EchoClient.class:		EchoClient.java
				@javac EchoClient.java

clean:
				@rm -rf *.class *~

info:
				@echo "(c) Roland Teodorowitsch (23 ago. 2013)"
